export const mountains = [
  {
    name: "Gerlachovský štít",
    alt: 2655,
    alt_source: "SÚGK 2011",
    diff: "expert",
    country: "SK",
    guide_required: true,
    lat: 49.1595,
    lng: 20.1344,
    time: "7–9 h",
    gain: "~1400 m",
    best_season: "Júl–september",
    nearest_hut: "Chata pri Zelenom plese (1551 m)",
    first_ascent: "1793 – Dávid Dénes a Thomas Mauksch",
    fun_fact: "Najvyšší vrch Karpát. Bol dlho považovaný za nižší než Lomnický štít – omyl pretrvával vyše 100 rokov.",
    wiki_title: "Gerlachovský štít",
    desc: "Najvyšší vrch Tatier a celých Karpát. Výstup je povinný len s licencovaným horským sprievodcom, trasa vedie exponovanými skalnatými žľabmi."
  },
  {
    name: "Lomnický štít",
    alt: 2634,
    alt_source: "SÚGK 2011",
    diff: "easy",
    country: "SK",
    guide_required: false,
    lat: 49.1953,
    lng: 20.2135,
    time: "—",
    gain: "—",
    best_season: "Celoročne (lanovka)",
    nearest_hut: "Hotel Lomnický štít (na vrchole)",
    first_ascent: "1793 – Robert Townson",
    fun_fact: "Na vrchole sa nachádza najvyššie položená meteorologická stanica v strednej Európe, nepretržite v prevádzke od roku 1957.",
    wiki_title: "Lomnický štít",
    desc: "Druhý najvyšší vrch Tatier, prístupný elektrickou ozubnicovou lanovkou z Tatranskej Lomnice. Na vrchole sídli meteorologická stanica a turistické centrum."
  },
  {
    name: "Rysy",
    alt: 2503,
    alt_source: "GUGiK / SÚGK",
    diff: "medium",
    country: "SK",
    guide_required: false,
    lat: 49.1797,
    lng: 20.0883,
    time: "5–6 h",
    gain: "~1100 m",
    best_season: "Júl–september",
    nearest_hut: "Chata pod Rysmi (2250 m) – najvyššia horská chata v SR",
    first_ascent: "1793 – bratia Hacquetovci",
    fun_fact: "Najvyšší bod, na ktorý vystúpil Vladimír Iľjič Lenin – v roku 1913 pri pobyte v Zakopanom.",
    wiki_title: "Rysy",
    desc: "Najvyšší turisticky prístupný vrchol na hranici Slovenska a Poľska. Obľúbený pre panoramatický výhľad a možnosť výstupu z oboch strán hranice."
  },
  {
    name: "Kriváň",
    alt: 2494,
    alt_source: "SÚGK 2011",
    diff: "medium",
    country: "SK",
    guide_required: false,
    lat: 49.1561,
    lng: 19.9939,
    time: "5–6 h",
    gain: "~1050 m",
    best_season: "Júl–september",
    nearest_hut: "Podbanské (výchozí bod, 900 m)",
    first_ascent: "1793 – Juraj Buchholtz ml.",
    fun_fact: "Každoročne sa tu koná Kriváňsky pochod, tradičný výstup slovenských turistov. Kriváň je symbolom Slovenska – zobrazený na slovenských euromincach.",
    wiki_title: "Kriváň",
    desc: "Symbol slovenského národa a jeden z najikonickejších vrcholov Tatier. Výstup z Podbanského je fyzicky náročný, technicky bezpečný."
  },
  {
    name: "Slavkovský štít",
    alt: 2452,
    alt_source: "SÚGK 2011",
    diff: "medium",
    country: "SK",
    guide_required: false,
    lat: 49.1711,
    lng: 20.2294,
    time: "4–5 h",
    gain: "~900 m",
    best_season: "Jún–október",
    nearest_hut: "Zamkovského chata (1475 m)",
    first_ascent: "Neznámy, pravdepodobne 18. storočie",
    fun_fact: "Z vrcholu je za jasného dňa vidieť až po Nízke Tatry a Fatru. Nazvaný podľa obce Slavkov pri Smokovci.",
    wiki_title: "Slavkovský štít",
    desc: "Dominanta nad Starým Smokovcom s výborným výhľadom na celé Vysoké Tatry. Trasa prechádza Slavkovským sedlom a ponúka rôznorodý terén."
  },
  {
    name: "Ľadový štít",
    alt: 2627,
    alt_source: "SÚGK 2011",
    diff: "expert",
    country: "SK",
    guide_required: true,
    lat: 49.1867,
    lng: 20.1756,
    time: "8–10 h",
    gain: "~1500 m",
    best_season: "Júl–august",
    nearest_hut: "Zbojnícka chata (1960 m)",
    first_ascent: "1793 – Thomas Mauksch a Johann Czirbus",
    fun_fact: "Tretí najvyšší vrchol Tatier. Názov pochádza od ľadovca v severnej stene, ktorý bol v 18. storočí výrazne väčší než dnes.",
    wiki_title: "Ľadový štít",
    desc: "Tretí najvyšší vrch Tatier s technicky veľmi náročným výstupom. Vyžaduje horolezeckú výzbroj, skúsenosti so skalným terénom a odporúča sa sprievodca."
  },
  {
    name: "Mengusovský štít",
    alt: 2438,
    alt_source: "SÚGK 2011",
    diff: "expert",
    country: "SK",
    guide_required: true,
    lat: 49.1697,
    lng: 20.1072,
    time: "7–9 h",
    gain: "~1200 m",
    best_season: "Júl–august",
    nearest_hut: "Popradské pleso (1494 m)",
    first_ascent: "1902 – Ludwig Rothaug",
    fun_fact: "Vrch sa tyčí priamo nad Popradským plesom. Pri výstupe sa prechádza cez Mengusovské sedlo, jedno z najexponovanejších v Tatrách.",
    wiki_title: "Mengusovský štít",
    desc: "Izolovaný štít nad Popradským plesom s exponovanými skalnatými úsekmi. Výstup vyžaduje horolezecké schopnosti a znalosť terénu."
  },
  {
    name: "Furkotský štít",
    alt: 2405,
    alt_source: "SÚGK 2011",
    diff: "hard",
    country: "SK",
    guide_required: false,
    lat: 49.1531,
    lng: 20.0694,
    time: "6–7 h",
    gain: "~1000 m",
    best_season: "Júl–september",
    nearest_hut: "Chata pod Soliskom (1840 m)",
    first_ascent: "1902 – Gyula Hefty",
    fun_fact: "V blízkosti Furkotskej doliny sa nachádza päť Furkotských plies – sústava plies s výnimočnou modrou farbou vody.",
    wiki_title: "Furkotský štít",
    desc: "Výrazný skalnatý vrchol v Mlynickej doline. Výstup kombinuje turistické chodníky s nenáročným lezením a ponúka panoramatický výhľad."
  },
  {
    name: "Svinica",
    alt: 2301,
    alt_source: "SÚGK 2011",
    diff: "hard",
    country: "SK",
    guide_required: false,
    lat: 49.2003,
    lng: 20.1792,
    time: "5–6 h",
    gain: "~900 m",
    best_season: "Jún–september",
    nearest_hut: "Téryho chata (2015 m)",
    first_ascent: "1904 – Ján Hunsdorfer",
    fun_fact: "Svinica je populárna medzi horolezeckými školami vďaka svojmu prístupnému, no technicky zaujímavému terénu.",
    wiki_title: "Svinica",
    desc: "Horský vrchol nad Veľkou studenou dolinou s nádhernými výhľadmi na centrálne Tatry. Trasa obsahuje skalnaté úseky vyžadujúce dobrú kondíciu."
  },
  {
    name: "Giewont",
    alt: 1895,
    alt_source: "GUGiK 2010",
    diff: "medium",
    country: "PL",
    guide_required: false,
    lat: 49.2519,
    lng: 19.9336,
    time: "4–5 h",
    gain: "~870 m",
    best_season: "Máj–október",
    nearest_hut: "Schronisko na Hali Kondratowej (1333 m)",
    first_ascent: "1867 – Walery Eliasz Radzikowski",
    fun_fact: "15-metrový oceľový kríž na vrchole bol vztyčený v roku 1901 a vážil 630 kg. Za búrky je vrchol extrémne nebezpečný kvôli bleskovým úderom.",
    wiki_title: "Giewont",
    desc: "Legendárny vrch nad Zakopané, nazývaný Spiaci rytier. Na vrchole stojí mohutný kovový kríž, viditeľný z celého mesta a okolia."
  },
  {
    name: "Kasprowy Wierch",
    alt: 1987,
    alt_source: "GUGiK 2010",
    diff: "easy",
    country: "PL",
    guide_required: false,
    lat: 49.2317,
    lng: 19.9819,
    time: "—",
    gain: "—",
    best_season: "Celoročne (lanovka)",
    nearest_hut: "Schronisko na Hali Gąsienicowej (1500 m)",
    first_ascent: "1830 – Stanisław Staszic (prvý opis výstupu)",
    fun_fact: "Lanovka na Kasprowy Wierch bola otvorená v roku 1936 a stala sa prvou pohraničnou lanovkou v Európe. Meteorologická stanica tu meria snehovú pokrývku od roku 1938.",
    wiki_title: "Kasprowy Wierch",
    desc: "Obľúbená turistická destinácia dostupná lanovkou zo Zakopané. Pohraničný vrch s meteorologickou stanicou a lyžiarskym strediskom."
  },
  {
    name: "Kościelec",
    alt: 2155,
    alt_source: "GUGiK 2010",
    diff: "hard",
    country: "PL",
    guide_required: false,
    lat: 49.2256,
    lng: 20.0047,
    time: "5–6 h",
    gain: "~850 m",
    best_season: "Júl–september",
    nearest_hut: "Schronisko w Dolinie Pięciu Stawów Polskich (1671 m)",
    first_ascent: "1895 – Klimek Bachleda a Karol Potkański",
    fun_fact: "Kościelec je považovaný za jeden z najkrajších tatranských vrcholov vďaka svojej ihličkovitej siluete. Záverečný skalný hrebeň je veľmi exponovaný.",
    wiki_title: "Kościelec",
    desc: "Ostrý skalnatý vrchol nad Čiernym plesou, považovaný za jeden z najkrajších v poľských Tatrách. Záverečný úsek vyžaduje istenie a skúsenosti so skalnatým terénom."
  },
  {
    name: "Vysoká",
    alt: 2560,
    alt_source: "SÚGK 2011",
    diff: "expert",
    country: "SK",
    guide_required: true,
    lat: 49.1694,
    lng: 20.1006,
    time: "8–10 h",
    gain: "~1300 m",
    best_season: "Júl–august",
    nearest_hut: "Popradské pleso (1494 m)",
    first_ascent: "1902 – Gyula Komarnicki",
    fun_fact: "Vysoká má charakteristickú pyramidálnu siluetu, ktorá je dobre viditeľná z diaľnice pri Poprade. Jej severná stena patrí k najdlhším v Tatrách.",
    wiki_title: "Vysoká (Tatry)",
    desc: "Štíhly pyramidálny vrchol nad Mengusovskou dolinou s dlhou severnou stenou. Jeden z najnáročnejších horolezeckých výstupov vo Vysokých Tatrách."
  },
  {
    name: "Východná Vysoká",
    alt: 2429,
    alt_source: "SÚGK 2011",
    diff: "hard",
    country: "SK",
    guide_required: false,
    lat: 49.1714,
    lng: 20.1081,
    time: "6–8 h",
    gain: "~1100 m",
    best_season: "Júl–september",
    nearest_hut: "Popradské pleso (1494 m)",
    first_ascent: "1906 – Dr. Siegmund Haberfeld",
    fun_fact: "Napriek svojej výške je Východná Vysoká menej navštevovaná ako susedná Vysoká, čo z nej robí vhodný cieľ pre tých, čo hľadajú samotu.",
    wiki_title: "Východná Vysoká",
    desc: "Technicky náročný výstup s expozíciou v skalnom teréne nad Mengusovskou dolinou. Ponúka výnimočný výhľad na centrálne Tatry."
  },
  {
    name: "Veľký Mengusovský štít",
    alt: 2393,
    alt_source: "SÚGK 2011",
    diff: "expert",
    country: "SK",
    guide_required: true,
    lat: 49.1731,
    lng: 20.1128,
    time: "7–9 h",
    gain: "~1150 m",
    best_season: "Júl–august",
    nearest_hut: "Popradské pleso (1494 m)",
    first_ascent: "1906 – Alfred Martin",
    fun_fact: "Massív Mengusovských štítov tvorí prirodzenú stenu, ktorá uzatvára Popradskú kotlinu zo severu. Výstup je náročný aj pre skúsených lezecov.",
    wiki_title: "Mengusovský štít",
    desc: "Skalnatý vrchol v oblasti Mengusovskej doliny. Výstup vyžaduje pokročilé horolezecké schopnosti a dokonalú znalosť terénu."
  },
  {
    name: "Świnica",
    alt: 2301,
    alt_source: "GUGiK 2010",
    diff: "hard",
    country: "PL",
    guide_required: false,
    lat: 49.2183,
    lng: 19.9997,
    time: "5–6 h",
    gain: "~900 m",
    best_season: "Júl–september",
    nearest_hut: "Schronisko na Hali Gąsienicowej (1500 m)",
    first_ascent: "1867 – Eugeniusz Janota",
    fun_fact: "Świnica leží presne na hranici medzi Slovenskom a Poľskom. Z vrcholu je vidieť Morské oko aj všetky Gąsienicowé plesá naraz.",
    wiki_title: "Świnica",
    desc: "Pohraničný vrch prístupný z poľskej strany cez Świnicką Przełęcz. Excelentné výhľady na Morské oko aj Gąsienicowé plesá."
  },
  {
    name: "Kopieniec Wielki",
    alt: 1328,
    alt_source: "GUGiK 2010",
    diff: "easy",
    country: "PL",
    guide_required: false,
    lat: 49.2831,
    lng: 20.0003,
    time: "2–3 h",
    gain: "~400 m",
    best_season: "Apríl–november",
    nearest_hut: "—",
    first_ascent: "Neurčený, turisticky frekventovaný od 19. storočia",
    fun_fact: "Z rozhľadne na vrchole sa v zimný jasný deň dá vidieť celý hrebeň Vysokých Tatier od Gerlachovského štítu až po Ľadový štít.",
    wiki_title: "Kopieniec Wielki",
    desc: "Nízky tatranský vrch s rozhľadňou a výnimočným výhľadom na Zakopané a Giewont. Ideálny pre rodiny s deťmi a nenáročných turistov."
  },
  {
    name: "Veľká Svišťovka",
    alt: 1831,
    alt_source: "SÚGK 2011",
    diff: "easy",
    country: "SK",
    guide_required: false,
    lat: 49.1261,
    lng: 20.0644,
    time: "3–4 h",
    gain: "~600 m",
    best_season: "Máj–október",
    nearest_hut: "Chata Kapitána Nálepku (1695 m)",
    first_ascent: "Neurčený, turisticky frekventovaný od konca 19. storočia",
    fun_fact: "V okolí Veľkej Svišťovky sa rozkladajú rozsiahle kosodrevinové porasty, ktoré sú domovom početných kolónií svišťov – odtiaľ pochádza jej názov.",
    wiki_title: "Veľká Svišťovka",
    desc: "Pokojný výstup zo Štrbského plesa s pekným výhľadom na Vysoké Tatry. Vhodný pre začiatočníkov a rodiny, trasa vedie dobre značenými chodníkmi."
  },
  {
    name: "Ostrý Roháč",
    alt: 2088,
    alt_source: "SÚGK 2011",
    diff: "hard",
    country: "SK",
    guide_required: false,
    lat: 49.1847,
    lng: 19.6806,
    time: "5–6 h",
    gain: "~900 m",
    best_season: "Jún–september",
    nearest_hut: "Roháčska chata (1565 m)",
    first_ascent: "1894 – Carl Englisch",
    fun_fact: "Ostrý Roháč je súčasťou popularnej hrebeňovky cez Roháče, ktorú mnohí turisti opisujú ako najkrajší jednodenný výlet v slovenských Tatrách.",
    wiki_title: "Ostrý Roháč",
    desc: "Najvyšší vrchol Západných Tatier s panoramatickým výhľadom na Oravskú priehradu a celé Tatry. Hrebeňový chodník cez Roháče je turisticky atraktívny."
  },
  {
    name: "Baníkov",
    alt: 2178,
    alt_source: "SÚGK 2011",
    diff: "medium",
    country: "SK",
    guide_required: false,
    lat: 49.2139,
    lng: 19.6325,
    time: "4–5 h",
    gain: "~800 m",
    best_season: "Jún–október",
    nearest_hut: "Chata Zverovka (890 m)",
    first_ascent: "Neurčený, turisticky prístupný od konca 19. storočia",
    fun_fact: "Z Baníkova je výnimočný výhľad na Liptovskú Maru a za jasného počasia aj na Nízke Tatry a Malú Fatru. Vrch bol pomenovaný po baníkoch z okolia.",
    wiki_title: "Baníkov",
    desc: "Dominantný vrch Západných Tatier s rozsiahlym výhľadom na Liptovskú Maru. Výstup z Osobitej je fyzicky nenáročný a vhodný pre zdatnejších turistov."
  }
];
